name: CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
          cache: sbt
      - name: Run tests
        run: sbt -v "test"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
          cache: sbt
      - name: Run scalafix
        run: sbt -v "scalafixAll --check"
      - name: Run scalafmt
        run: sbt -v "scalafmtCheck"
      - uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: "**/*.md"
