name: Lint

on:
  push:
    branches:
      - "*"

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run scalafmt
        uses: jrouly/scalafmt-native-action@v2
        with:
          version: "3.7.14"
          arguments: "--list"
